-- Additive migration; existing Q&A columns and RPC remain compatible.
-- Run manually before upload; this does not remove existing documents.
create extension if not exists vector;
create table if not exists document_chunks (
  id bigint generated by default as identity primary key,
  content text not null,
  filename text not null,
  page_number integer not null,
  embedding vector(1536)
);
alter table document_chunks add column if not exists chunk_id text;
alter table document_chunks add column if not exists metadata jsonb not null default '{}'::jsonb;
create unique index if not exists document_chunks_chunk_id_key on document_chunks(chunk_id);
create index if not exists document_chunks_metadata_idx on document_chunks using gin(metadata);
-- Prevent direct anonymous table access; backend uses the service role key.
alter table document_chunks enable row level security;
-- Older document revisions remain stored. Select the desired document_version
-- for quiz generation; the existing Q&A RPC still searches all stored versions.
